import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/* ✅ CORRECT local font setup */
const skModernist = localFont({
  src: [
    {
      path: "../public/fonts/SK-Modernist-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/SK-Modernist-Bold.otf",
      weight: "700",
      style: "bold",
    },
  ],
  variable: "--font-sk-modernist",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${skModernist.variable}
          antialiased
        `}
      >
        {children}
      </body>
    </html>
  );
}
